# Generated by Django 3.1.4 on 2020-12-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='job_description',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
