# Generated by Django 3.1.4 on 2020-12-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20201214_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(null=True, verbose_name='Check out'),
        ),
    ]
