# Generated by Django 3.1.4 on 2020-12-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20201214_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(null=True, verbose_name='Check In'),
        ),
    ]
