# Generated by Django 3.1.4 on 2020-12-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20201215_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(null=True, verbose_name='attended'),
        ),
    ]
