# Generated by Django 3.1.4 on 2020-12-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_attendance_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='from_date',
            field=models.DateField(verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='to_date',
            field=models.DateField(verbose_name='To Date'),
        ),
    ]
