# Generated by Django 3.1.4 on 2020-12-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20201215_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='duration',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
