# Generated by Django 3.1.4 on 2020-12-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20201215_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='day_off',
            field=models.BooleanField(null=True, verbose_name='attended'),
        ),
    ]
