# Generated by Django 3.1.4 on 2020-12-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_attendance_vacation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='vacation_id',
            new_name='vacation',
        ),
    ]
